### ISSUE TITLE
License Discussion

### ISSUE THREAD

**Issue by heidi-ye** [UBC-MDS/sptidy#35]
Opening issue for license discussion. 

The main discussion is part of the Python issue [here](https://github.com/UBC-MDS/sktidy/issues/41).

**Comment by anodaini** [comment]
My suggestion is that we keep the MIT license. Since our package idea is adapted from the broom package (an open-source package), I don't think we would want to put restrictions to use, copy, modify, ..., or sell, yet we still want to free ourselves of liability so I think we should keep the MIT license. Thoughts?

**Comment by JacobMcFarlane** [comment]
Yup I'm good with MIT!
